server:
  port: 8080

spring:
  application:
    name: api-gateway
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Enable more detailed logging
logging:
  level:
    com.eventorganizer.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
      
# Proxy service URLs
app:
  service-urls:
    auth-service: http://localhost:8084
    user-service: http://localhost:8085
    service-provider-service: http://localhost:8081
    booking-service: http://localhost:8082
    review-service: http://localhost:8083 